//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunboundImageCreator.App.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GunboundImageCreator.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al dar click en registrarte, aceptas los terminos de uso y politicas de privacidad, para leer, dar click en leer..
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar fotograma.
        /// </summary>
        public static string AddKeyFrameLabel {
            get {
                return ResourceManager.GetString("AddKeyFrameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Bmp.
        /// </summary>
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta.
        /// </summary>
        public static string AlertLabel {
            get {
                return ResourceManager.GetString("AlertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alfa.
        /// </summary>
        public static string AlphaLabel {
            get {
                return ResourceManager.GetString("AlphaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animación.
        /// </summary>
        public static string AnimationLabel {
            get {
                return ResourceManager.GetString("AnimationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animación (vista previa).
        /// </summary>
        public static string AnimationPreviewLabel {
            get {
                return ResourceManager.GetString("AnimationPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de animación ya existe!.
        /// </summary>
        public static string AnimationTypeExists {
            get {
                return ResourceManager.GetString("AnimationTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de animación.
        /// </summary>
        public static string AnimationTypeLabel {
            get {
                return ResourceManager.GetString("AnimationTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación no registrada, se le solicitará un numero de serie.
        /// </summary>
        public static string AppNotRegistered {
            get {
                return ResourceManager.GetString("AppNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar (vista previa).
        /// </summary>
        public static string AvatarPreviewLabel {
            get {
                return ResourceManager.GetString("AvatarPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fondo {0}.
        /// </summary>
        public static string BackgroundHeaderLabel {
            get {
                return ResourceManager.GetString("BackgroundHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fondo.
        /// </summary>
        public static string BackgroundLabel {
            get {
                return ResourceManager.GetString("BackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de serie ha sido bloqueado.
        /// </summary>
        public static string BlockedSerialNumber {
            get {
                return ResourceManager.GetString("BlockedSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma tu contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coord X.
        /// </summary>
        public static string CoordXLabel {
            get {
                return ResourceManager.GetString("CoordXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coord Y.
        /// </summary>
        public static string CoordYLabel {
            get {
                return ResourceManager.GetString("CoordYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright © 2012 Ar2roMx. Todos los derechos reservados..
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear animación.
        /// </summary>
        public static string CreateAnimationLabel {
            get {
                return ResourceManager.GetString("CreateAnimationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear línea de tiempo.
        /// </summary>
        public static string CreateTimeLineLabel {
            get {
                return ResourceManager.GetString("CreateTimeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar linea de tiempo.
        /// </summary>
        public static string DeleteTimeLineLabel {
            get {
                return ResourceManager.GetString("DeleteTimeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración.
        /// </summary>
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor.
        /// </summary>
        public static string EditorLabel {
            get {
                return ResourceManager.GetString("EditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email ya está en uso. Elige otro.
        /// </summary>
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de animación no puede ir vacío.
        /// </summary>
        public static string EmptyAnimationType {
            get {
                return ResourceManager.GetString("EmptyAnimationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string EnglishLabel {
            get {
                return ResourceManager.GetString("EnglishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo de conexion.
        /// </summary>
        public static string ErrorConnectingLabel {
            get {
                return ResourceManager.GetString("ErrorConnectingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error al intentarse conectar al servidor..
        /// </summary>
        public static string ErrorConnectingServer {
            get {
                return ResourceManager.GetString("ErrorConnectingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al procesar el archivo.
        /// </summary>
        public static string ErrorProcessingFile {
            get {
                return ResourceManager.GetString("ErrorProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de vencimiento.
        /// </summary>
        public static string ExpirationDateLabel {
            get {
                return ResourceManager.GetString("ExpirationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        public static string ExportLabel {
            get {
                return ResourceManager.GetString("ExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El uso de datos falsos en la suscripcion, causará la cancelación de la misma.
        /// </summary>
        public static string FakeDataAtSignup {
            get {
                return ResourceManager.GetString("FakeDataAtSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string FileLabel {
            get {
                return ResourceManager.GetString("FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningun archivo seleccionado.
        /// </summary>
        public static string FileNotOpenLabel {
            get {
                return ResourceManager.GetString("FileNotOpenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La compuradora en la que se registro el producto es diferente, ¿Cambió el hardware?.
        /// </summary>
        public static string HardwareIdMismatch {
            get {
                return ResourceManager.GetString("HardwareIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alto.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen {0}.
        /// </summary>
        public static string ImageHeaderLabel {
            get {
                return ResourceManager.GetString("ImageHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string ImageLabel {
            get {
                return ResourceManager.GetString("ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagenes.
        /// </summary>
        public static string ImagesLabel {
            get {
                return ResourceManager.GetString("ImagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o la contraseña con son incorrectos!.
        /// </summary>
        public static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserta tu Email.
        /// </summary>
        public static string InsertEmail {
            get {
                return ResourceManager.GetString("InsertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserta tu nombre.
        /// </summary>
        public static string InsertFirstName {
            get {
                return ResourceManager.GetString("InsertFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserta tu apellido.
        /// </summary>
        public static string InsertLastName {
            get {
                return ResourceManager.GetString("InsertLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserta tu nickname.
        /// </summary>
        public static string InsertNickname {
            get {
                return ResourceManager.GetString("InsertNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserta tu nickname o email.
        /// </summary>
        public static string InsertNickOrEmail {
            get {
                return ResourceManager.GetString("InsertNickOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserta una contraseña.
        /// </summary>
        public static string InsertPassword {
            get {
                return ResourceManager.GetString("InsertPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserta el numero de serie.
        /// </summary>
        public static string InsertSerialNumber {
            get {
                return ResourceManager.GetString("InsertSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email no es válido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre solo puede contener letras y espacios.
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido solo puede contener letras y espacios.
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname solo puede contener letras y numeros.
        /// </summary>
        public static string InvalidNickname {
            get {
                return ResourceManager.GetString("InvalidNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto no existe.
        /// </summary>
        public static string InvalidProduct {
            get {
                return ResourceManager.GetString("InvalidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string InvalidPwdConfirm {
            get {
                return ResourceManager.GetString("InvalidPwdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de serie inválido.
        /// </summary>
        public static string InvalidSerialNumber {
            get {
                return ResourceManager.GetString("InvalidSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotograma.
        /// </summary>
        public static string KeyFrameLabel {
            get {
                return ResourceManager.GetString("KeyFrameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de lenguaje.
        /// </summary>
        public static string LanguageChangedLabel {
            get {
                return ResourceManager.GetString("LanguageChangedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido(s).
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El lenguaje se cambio correctamente. Reinicie el programa para aplicar cambios..
        /// </summary>
        public static string LenguageChanged {
            get {
                return ResourceManager.GetString("LenguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de la licencia.
        /// </summary>
        public static string LicenceInfoTitle {
            get {
                return ResourceManager.GetString("LicenceInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia.
        /// </summary>
        public static string LicenceLabel {
            get {
                return ResourceManager.GetString("LicenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email / Nickname.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] mb00000 {
            get {
                object obj = ResourceManager.GetObject("mb00000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] mh00000 {
            get {
                object obj = ResourceManager.GetObject("mh00000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string NewLabel {
            get {
                return ResourceManager.GetString("NewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nickname ya está en uso. Elige otro.
        /// </summary>
        public static string NicknameInUse {
            get {
                return ResourceManager.GetString("NicknameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string NicknameLabel {
            get {
                return ResourceManager.GetString("NicknameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguna.
        /// </summary>
        public static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir animación.
        /// </summary>
        public static string OpenAnimationLabel {
            get {
                return ResourceManager.GetString("OpenAnimationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        public static string OpenLabel {
            get {
                return ResourceManager.GetString("OpenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string PasswordConfirmLabel {
            get {
                return ResourceManager.GetString("PasswordConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pago de la licencia no se ha realizado, haga el pago correspondiente y contacte al administrador..
        /// </summary>
        public static string PaymentNotMade {
            get {
                return ResourceManager.GetString("PaymentNotMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Português.
        /// </summary>
        public static string PortuguesLabel {
            get {
                return ResourceManager.GetString("PortuguesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has adquirido una licencia recientemente..
        /// </summary>
        public static string PurchaseError {
            get {
                return ResourceManager.GetString("PurchaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer terminos de uso y politicas de privacidad.
        /// </summary>
        public static string ReadTermsLabel {
            get {
                return ResourceManager.GetString("ReadTermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar aplicación.
        /// </summary>
        public static string RegisterAppTitle {
            get {
                return ResourceManager.GetString("RegisterAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar fotograma.
        /// </summary>
        public static string RemoveKeyFrameLabel {
            get {
                return ResourceManager.GetString("RemoveKeyFrameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir.
        /// </summary>
        public static string RepeatLabel {
            get {
                return ResourceManager.GetString("RepeatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        public static string ResetLabel {
            get {
                return ResourceManager.GetString("ResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información de su computadora se guardo correctamente en el portapapeles.
        ///
        ///Enviar al administrador..
        /// </summary>
        public static string SavedPcInfo {
            get {
                return ResourceManager.GetString("SavedPcInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar folder.
        /// </summary>
        public static string SelectFolderLabel {
            get {
                return ResourceManager.GetString("SelectFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de serie.
        /// </summary>
        public static string SerialNumberLabel {
            get {
                return ResourceManager.GetString("SerialNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string SessionLabel {
            get {
                return ResourceManager.GetString("SessionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al procesar su solicitud, intenta mas tarde..
        /// </summary>
        public static string SignupFailed {
            get {
                return ResourceManager.GetString("SignupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string SignupLabel {
            get {
                return ResourceManager.GetString("SignupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su registro se ha completado correctamente!.
        /// </summary>
        public static string SignupSuccess {
            get {
                return ResourceManager.GetString("SignupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string SignupWindowTitle {
            get {
                return ResourceManager.GetString("SignupWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple.
        /// </summary>
        public static string SimpleLabel {
            get {
                return ResourceManager.GetString("SimpleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string SpanishLabel {
            get {
                return ResourceManager.GetString("SpanishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang2058\deflangfe2058\themelang2058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string TermsOfUseRtf {
            get {
                return ResourceManager.GetString("TermsOfUseRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por registrar el producto.
        /// </summary>
        public static string ThanksForRegister {
            get {
                return ResourceManager.GetString("ThanksForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transparencia.
        /// </summary>
        public static string TransparencyTypeLabel {
            get {
                return ResourceManager.GetString("TransparencyTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tiempo de prueba ha finalizado. Contacte al administrador para contratar una licencia.
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error desconocido.
        /// </summary>
        public static string UnknowError {
            get {
                return ResourceManager.GetString("UnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una actualización disponible. Ejecute el actualizador para obtener la ultima versión..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Probar avatar.
        /// </summary>
        public static string WearAvatarLabel {
            get {
                return ResourceManager.GetString("WearAvatarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ar2roMx Image Creator.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
